require 'css_compare/css/component/value'
require 'css_compare/css/component/property'
require 'css_compare/css/component/selector'
require 'css_compare/css/component/keyframes_selector'
require 'css_compare/css/component/keyframes'
require 'css_compare/css/component/supports'
